name: 'Telegram Group Chat Action'
description: 'Inform the telegram group chat of new actions in repository'
inputs:
  chat-id:
    description: group or single chat id(you can get it on the url of the chat)
    required: true
  token-bot:
    description: bot token created by BotFather on Telegram
    required: true
  message_thread_id:
    description: chat thread/topic id(the number id of topic)
    required: false
  text:
    description: bot default text
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
