name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - run: |
        npm install -g esbuild && npm ci
#        npm run build

    - name: SendMessage
      uses: ./ # Replace with the appropriate action you intend to use
      with:
        bot-token: ${{ secrets.TELEGRAM_TOKEN }}
        chat-id: ${{ secrets.TELEGRAM_CHAT }}
        message_thread_id: ${{ secrets.MESSAGE_THREAD_ID }}
        text: '
          The ${{ github.event_name }} event triggered second step. 
          show the github variable ref: ${{ github.ref }} 
          show the github variable commit: ${{ github.sha }} 
          show the github variable ref: {{ commit.ref }} 
          show the github variable commit: {{ commit.sha }} 
          Commit Message: ${{ github.event.head_commit.message }}'
